### ISSUE TITLE
Uncaught TypeError: Cannot read property 'Event' of undefined

### ISSUE THREAD

**Issue by pi-ron** [GianlucaGuarini/Tocca.js#37]
Hi,

I'm struggling to get this script to work.  Using with jQuery 1.9.

If I click anywhere on a page, I get `Uncaught TypeError: Cannot read property 'Event' of undefined`

![Chrome inspecting error line](https://cloud.githubusercontent.com/assets/766926/15691122/6f26a91e-27ca-11e6-9a2d-7d8cc6278914.png)

**Comment by twerthmueller** [comment]
I had the same problem, because we do not use $ as a prefix for jQuery to prevent problems between different libraries.

You have just to replace the $ char with jQuery:
`customEvent = $.Event(eventName, {originalEvent: originalEvent})`
to
`customEvent = jQuery.Event(eventName, {originalEvent: originalEvent})`

I hope this get fixed in the lib soon.

**Comment by GianlucaGuarini** [comment]
@twerthmueller could you please make a pull request?

**Comment by twerthmueller** [comment]
Sure, I created a pull request: https://github.com/GianlucaGuarini/Tocca.js/pull/38
